http:
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer-when-downgrade"
        customRequestHeaders:
          X-Forwarded-Proto: "https"

  routers:
    api:
      rule: "Host(`api.morphyimg.com`)"
      service: "backend"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "default-headers"

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:3000"
